# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'edititem.ui'
#
# Created: Thu Jun 30 17:37:43 2011
#      by: PyQt4 UI code generator 4.8.3
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    _fromUtf8 = lambda s: s

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName(_fromUtf8("MainWindow"))
        MainWindow.resize(445, 245)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(MainWindow.sizePolicy().hasHeightForWidth())
        MainWindow.setSizePolicy(sizePolicy)
        MainWindow.setMinimumSize(QtCore.QSize(445, 245))
        MainWindow.setMaximumSize(QtCore.QSize(16777215, 256))
        self.centralwidget = QtGui.QWidget(MainWindow)
        self.centralwidget.setObjectName(_fromUtf8("centralwidget"))
        self.verticalLayout = QtGui.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setSpacing(0)
        self.verticalLayout.setMargin(0)
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.gridLayout = QtGui.QGridLayout()
        self.gridLayout.setSpacing(2)
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.label_2 = QtGui.QLabel(self.centralwidget)
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.gridLayout.addWidget(self.label_2, 1, 0, 1, 1)
        self.label = QtGui.QLabel(self.centralwidget)
        self.label.setObjectName(_fromUtf8("label"))
        self.gridLayout.addWidget(self.label, 2, 0, 1, 1)
        self.label_3 = QtGui.QLabel(self.centralwidget)
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.gridLayout.addWidget(self.label_3, 3, 0, 1, 1)
        self.label_4 = QtGui.QLabel(self.centralwidget)
        self.label_4.setObjectName(_fromUtf8("label_4"))
        self.gridLayout.addWidget(self.label_4, 4, 0, 1, 1)
        self.label_5 = QtGui.QLabel(self.centralwidget)
        self.label_5.setObjectName(_fromUtf8("label_5"))
        self.gridLayout.addWidget(self.label_5, 5, 0, 1, 1)
        self.label_6 = QtGui.QLabel(self.centralwidget)
        self.label_6.setObjectName(_fromUtf8("label_6"))
        self.gridLayout.addWidget(self.label_6, 6, 0, 1, 1)
        self.lineHost = QtGui.QLineEdit(self.centralwidget)
        self.lineHost.setObjectName(_fromUtf8("lineHost"))
        self.gridLayout.addWidget(self.lineHost, 1, 1, 1, 1)
        self.linePort = QtGui.QLineEdit(self.centralwidget)
        self.linePort.setObjectName(_fromUtf8("linePort"))
        self.gridLayout.addWidget(self.linePort, 2, 1, 1, 1)
        self.lineRemDir = QtGui.QLineEdit(self.centralwidget)
        self.lineRemDir.setObjectName(_fromUtf8("lineRemDir"))
        self.gridLayout.addWidget(self.lineRemDir, 3, 1, 1, 1)
        self.lineHomeDir = QtGui.QLineEdit(self.centralwidget)
        self.lineHomeDir.setObjectName(_fromUtf8("lineHomeDir"))
        self.gridLayout.addWidget(self.lineHomeDir, 4, 1, 1, 1)
        self.lineLogin = QtGui.QLineEdit(self.centralwidget)
        self.lineLogin.setObjectName(_fromUtf8("lineLogin"))
        self.gridLayout.addWidget(self.lineLogin, 5, 1, 1, 1)
        self.linePwd = QtGui.QLineEdit(self.centralwidget)
        self.linePwd.setObjectName(_fromUtf8("linePwd"))
        self.gridLayout.addWidget(self.linePwd, 6, 1, 1, 1)
        self.lineType = QtGui.QComboBox(self.centralwidget)
        self.lineType.setObjectName(_fromUtf8("lineType"))
        self.gridLayout.addWidget(self.lineType, 0, 1, 1, 1)
        self.label_7 = QtGui.QLabel(self.centralwidget)
        self.label_7.setObjectName(_fromUtf8("label_7"))
        self.gridLayout.addWidget(self.label_7, 0, 0, 1, 1)
        self.verticalLayout.addLayout(self.gridLayout)
        self.horizontalLayout_2 = QtGui.QHBoxLayout()
        self.horizontalLayout_2.setObjectName(_fromUtf8("horizontalLayout_2"))
        spacerItem = QtGui.QSpacerItem(324, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem)
        self.horizontalLayout = QtGui.QHBoxLayout()
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        self.butExit = QtGui.QPushButton(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.butExit.sizePolicy().hasHeightForWidth())
        self.butExit.setSizePolicy(sizePolicy)
        self.butExit.setMinimumSize(QtCore.QSize(50, 0))
        self.butExit.setText(_fromUtf8(""))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(_fromUtf8(":/newPrefix/application-exit.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.butExit.setIcon(icon)
        self.butExit.setObjectName(_fromUtf8("butExit"))
        self.horizontalLayout.addWidget(self.butExit)
        self.butSave = QtGui.QPushButton(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.butSave.sizePolicy().hasHeightForWidth())
        self.butSave.setSizePolicy(sizePolicy)
        self.butSave.setMinimumSize(QtCore.QSize(50, 0))
        self.butSave.setText(_fromUtf8(""))
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(_fromUtf8(":/newPrefix/emblem-certified.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.butSave.setIcon(icon1)
        self.butSave.setObjectName(_fromUtf8("butSave"))
        self.horizontalLayout.addWidget(self.butSave)
        self.horizontalLayout_2.addLayout(self.horizontalLayout)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtGui.QStatusBar(MainWindow)
        self.statusbar.setObjectName(_fromUtf8("statusbar"))
        MainWindow.setStatusBar(self.statusbar)
        self.label_2.setBuddy(self.lineHost)
        self.label.setBuddy(self.linePort)
        self.label_3.setBuddy(self.lineRemDir)
        self.label_4.setBuddy(self.lineHomeDir)
        self.label_5.setBuddy(self.lineLogin)
        self.label_6.setBuddy(self.linePwd)
        self.label_7.setBuddy(self.lineHost)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)
        MainWindow.setTabOrder(self.lineHost, self.linePort)
        MainWindow.setTabOrder(self.linePort, self.lineRemDir)
        MainWindow.setTabOrder(self.lineRemDir, self.lineHomeDir)
        MainWindow.setTabOrder(self.lineHomeDir, self.lineLogin)
        MainWindow.setTabOrder(self.lineLogin, self.linePwd)
        MainWindow.setTabOrder(self.linePwd, self.butSave)
        MainWindow.setTabOrder(self.butSave, self.butExit)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(QtGui.QApplication.translate("MainWindow", "Детальные данные", None, QtGui.QApplication.UnicodeUTF8))
        self.label_2.setText(QtGui.QApplication.translate("MainWindow", "Хост:", None, QtGui.QApplication.UnicodeUTF8))
        self.label.setText(QtGui.QApplication.translate("MainWindow", "Порт:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_3.setText(QtGui.QApplication.translate("MainWindow", "Удл.каталог:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_4.setText(QtGui.QApplication.translate("MainWindow", "Дом.каталог:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_5.setText(QtGui.QApplication.translate("MainWindow", "Логин:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_6.setText(QtGui.QApplication.translate("MainWindow", "Пароль:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_7.setText(QtGui.QApplication.translate("MainWindow", "Тип:", None, QtGui.QApplication.UnicodeUTF8))

import images_rc
